// BlogType Enum (match your backend BlogType enum)
export enum BlogType {
  CODEFORCES = "CODEFORCES",
  CODECHEF = "CODECHEF",
  LEETCODE = "LEETCODE",
  ATCODER = "ATCODER",
  GRAPHS = "GRAPHS",
  TREES = "TREES",
  ADVANCED_DATA_STRUCTURES = "ADVANCED_DATA_STRUCTURES",
  FREQUENT_ALGORITHMS = "FREQUENT_ALGORITHMS",
  GAMING = "GAMING",
  PROJECT = "PROJECT",
  INTRO = "INTRO",
  OTHERS = "OTHERS",
}